### ISSUE TITLE
Incorrect slot representation for layman repositories

### ISSUE THREAD

**Issue by KetothXupack** [vaeth/eix#7] opened 2015-06-03 14:30 UTC
Hi,

There is a strange behavior with dynamic `SLOT` environment variable definitions (i.e `SLOT="$(get_version_component_range 1-2)"`) for layman-based overlays. 

It looks like such slots are valid for emerge:
```
# emerge dev-db/apache-cassandra-bin:2.1

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R   ~] dev-db/apache-cassandra-bin-2.1.5:2.1::fw-overlay  USE="-systemd" 0 KiB
```

However `eix` shows  these slots incorrectly if overlay added via `layman` and totally correct if overlay added via `PORTDIR_OVERLAY`:

```
# eix cassandra-bin
[?] dev-db/apache-cassandra-bin
     Available versions:  
     ((get_version_component_range 1-2)) (~)2.0.15[1] (~)2.1.5[1]
     (2.0)  (~)2.0.15[2]
     (2.1)  (~)2.1.5[2]
       {systemd}
     Installed versions:  2.0.15(2.0)[1](04:54:38 PM 05/28/2015)(-systemd) 2.1.1-r1[1](04:56:37 PM 05/28/2015)(-systemd) 2.1.5(2.1)[1](04:54:29 PM 05/28/2015)(-systemd)
     Homepage:            http://cassandra.apache.org/
     Description:         The Apache Cassandra database is the right choice when you need scalability and high availability without compromising performance.

[1] "fw-overlay" /var/lib/layman/fw-overlay
[2] "fw-overlay" /opt/overlays/no-hope/fw-overlay
```

**Comment by vaeth** [comment] 2015-06-03 18:49
It is known that the cache method "parse" does not work reliable.
Choose a better cache method, preferrably call egencache in advance, see section SPEEDUP on the eix man page.
The difference you observe between the way how you add overlays is that for some methods portage creates cache data in /var/cache/edb (which eix uses if it is available).

Closing, since this is all known behaviour and not a bug (at least not a bug which can be fixed).

**Closed by vaeth** 2015-06-03 18:49 UTC
