### ISSUE TITLE
/usr/bin/eix-sync: line 108: Something went wrong with ...: command not found

### ISSUE THREAD

**Issue by devurandom** [vaeth/eix#17] opened 2015-12-10 10:52 UTC
Since a while eix-sync outputs the following (excerpt):
```
/usr/bin/eix-sync: line 108: Something went wrong with einfo "Updating metadata of local overlay ...": command not found
/usr/bin/eix-sync: line 108: Something went wrong with /usr/bin/egencache --update --repo=local: No such file or directory
```

My `/etc/eix-sync.conf` is:
```eix-sync.conf
!einfo "Unpacking Gentoo repository ..."
!mountpoint -q /var/cache/portage/gentoo && umount /var/cache/portage/gentoo || true
!mount -t tmpfs none /var/cache/portage/gentoo
!unsquashfs -f -d /var/cache/portage/gentoo /var/cache/portage/gentoo.sqfs

@einfo "Packing Gentoo repository ..."
@rm /var/cache/portage/gentoo.sqfs
@nice -n5 mksquashfs /var/cache/portage/gentoo /var/cache/portage/gentoo.sqfs -comp lz4
@umount /var/cache/portage/gentoo

@einfo "Mounting Gentoo repository ..."
@/usr/local/bin/mount-portage.sh

@einfo "Updating metadata of local overlay ..."
@/usr/bin/egencache --update --repo=local
```

**Comment by vaeth** [comment] 2015-12-11 08:11
This shoul already be fixed in git master (>=eix-0.31.4)

**Comment by devurandom** [comment] 2015-12-11 10:14
Sorry, I forgot to mention: I am using eix-0.31.3.

I'll just wait for the update.

**Comment by vaeth** [comment] 2015-12-22 08:41
Closing since eix-0.31.4 is in the tree.
Feel free to re-open (or open a new bug if you cannot) if the issue is not solved.

**Closed by vaeth** 2015-12-22 08:41 UTC

**Comment by devurandom** [comment] 2015-12-22 08:52
It's fixed, I just updated and checked.
