### ISSUE TITLE
eix-remote reports 'could not read all eix cachefile' error

### ISSUE THREAD

**Issue by pluser** [vaeth/eix#6] opened 2015-04-04 11:37 UTC
```
% eix -V
0.30.7
```
I'm using the newest version.
```
% ls -al /var/cache/eix
total 0
drwxr-xr-x 1 portage portage   0 Apr  4 19:50 .
drwxr-xr-x 1 root    root    136 Apr  4 01:38 ..
```
The cache directory is clean.
```
% sudo eix-remote update
--2015-04-04 19:53:38--  http://gpo.zugaina.org/eix_cache/eix-cache.tbz2
Resolving gpo.zugaina.org... 176.31.182.181
Connecting to gpo.zugaina.org|176.31.182.181|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3257524 (3.1M) [text/plain]
Saving to: ‘eix-cache.tbz2’

eix-cache.tbz2                 100%[=====================================================>]   3.11M   618KB/s   in 7.3s

2015-04-04 19:53:46 (437 KB/s) - ‘eix-cache.tbz2’ saved [3257524/3257524]

 * Unpacking data
Can't find overlay */bgo-overlay in /tmp/eix-remote.07axpS3E/1/bgo-overlay.eix
Can't find overlay */gentoo in /tmp/eix-remote.07axpS3E/1/gentoo.eix
layman/abendbrot -> abendbrot
layman/abnorm -> abnorm
layman/activehome -> activehome
layman/ago -> ago
layman/aidecoe -> aidecoe
<...snip...>
layman/zugaina -> zugaina
layman/zx2c4 -> zx2c4
 * Output to remote database /var/cache/eix/remote.eix
 * Calling eix-update
Reading Portage settings ..
KEEP_VIRTUALS is ignored: there is no previous /var/cache/eix/portage.eix
Building database (/var/cache/eix/remote.eix) ..
[0] 'gentoo' /usr/portage/ (cache: eix)
     Reading Packages ..
Can't read cache file /var/cache/eix/portage.eix: No such file or directory
     Reading Packages ..
Can't read cache file /var/cache/eix/portage.eix: No such file or directory
     Reading Packages .. ABORTED!
[1] 'abendbrot' layman/abendbrot (cache: eix* /tmp/eix-remote.07axpS3E/1/abendbrot.eix [*/abendbrot])
     Reading Packages .. Finished
[2] 'abnorm' layman/abnorm (cache: eix* /tmp/eix-remote.07axpS3E/1/abnorm.eix [*/abnorm])
     Reading Packages .. Finished
<...snip...>
[477] 'zugaina' layman/zugaina (cache: eix* /tmp/eix-remote.07axpS3E/1/zugaina.eix [*/zugaina])
     Reading Packages .. Finished
[478] 'zx2c4' layman/zx2c4 (cache: eix* /tmp/eix-remote.07axpS3E/1/zx2c4.eix [*/zx2c4])
     Reading Packages .. Finished
Applying masks ..
Calculating hash tables ..
Writing database file /var/cache/eix/remote.eix ..
Database contains 28835 packages in 240 categories.
 * could not read all eix cachefiles of /var/cache/eix/remote.tar.bz2

Probably your eix cachefile was *not* updated successfully.
Unless the above messages suggest another cause or you specified a
wrong filename, the most likely cause of this is that the server uses
another eix version than you or produced broken data. Please check whether
EIX_REMOTEARCHIVE is a valid *.tar.bz2 archive containing eix cachefiles
(you can download it using fetch).
If this is not the case (but was freshly downloaded), please report a bug.
Note that the archive is *not* broken if only the cachefile format versions
differ: In that case only report a bug if the eix cachefile format versions
in the downloaded file are *older* than that of the most current ~x86 eix
version in the portage tree (but first retry after several days before
reporting such a bug to give the server maintainers a chance to upgrade
after a version bump of eix).
Conversely, if the downloaded versions are even newer than that supported by
your eix, you will have to upgrade to the most current ~x86 version of eix
to use eix-remote: This inconvenience cannot be avoided and is not a bug!
```
According to this message, eix-remote couldn't update the cache file.
but...
```
% ls -al /var/cache/eix
total 12084
drwxr-xr-x 1 portage portage      48 Apr  4 19:53 .
drwxr-xr-x 1 root    root        136 Apr  4 01:38 ..
-rw-rw-r-- 1 portage portage 9112403 Apr  4 19:54 remote.eix
-rw-rw-r-- 1 portage portage 3257524 Apr  4 14:37 remote.tar.bz2
```
It seems that the cache is updated.
```
% eix -R eix
[?] app-portage/eix
     Available versions:  ~0.27.6[5] ~0.29.3[7] 0.30.3^m[2] 0.30.4[2] **9999[1] **99999999*l[3] {clang debug +dep doc nls optimization security sqlite sqlite3 strong-optimization strong-security swap-remote tools zsh-completion LINGUAS="de ru"}
     Installed versions:  0.30.7(04:10:26 AM 04/04/2015)(dep nls sqlite -debug -doc -optimization -security -strong-optimization -strong-security -swap-remote -tools LINGUAS="-de -ru")
     Homepage:            https://github.com/vaeth/eix/
     Description:         Search and query ebuilds, portage incl. local settings, ext. overlays, version changes, and more

* app-portage/binki-eix-postsync
     Available versions:  0[4] 0[6]
     Homepage:            http://dev.gentoo.org/~binki
     Description:         Install /etc/portage/postsync.d/eix-update which is missing from app-portage/eix

[1] "arcon" layman/arcon
[2] "funtoo-overlay" layman/funtoo-overlay
[3] "mv" layman/mv
[4] "ohnobinki_overlay" layman/ohnobinki_overlay
[5] "paddymac" layman/paddymac
[6] "spike-community-overlay" layman/spike-community-overlay
[7] "vaca" layman/vaca

Found 2 matches.
```
The eix cache is updated correctly.
But what is that message? How to fix?

**Comment by vaeth** [comment] 2015-04-04 16:55
The problem is here:

> Can't find overlay */bgo-overlay in /tmp/eix-remote.07axpS3E/1/bgo-overlay.eix
> Can't find overlay */gentoo in /tmp/eix-remote.07axpS3E/1/gentoo.eix

The overlay path does not match to the filename (which is what eix-remote expected).
(And indeed, you will see that the bgo-overlay has not been added to your database, that is, the error is justified, although the message might be misleading.)

In current eix git master (>=eix-0.30.8) now the overlay path is not used, but instead the first overlay in the file is used. Moreover (since "gentoo.eix" contains no overlay at all), the file "gentoo.eix" is ignored.

I hope that both changes do not break with
http://dev.gentooexperimental.org/eix_cache/eix-caches.tbz2

Currently I cannot test this, since the file cannot be downloaded. I do not know whether only the server is down, currently, or whether the service has been completely abandoned.

**Comment by pluser** [comment] 2015-05-10 17:47
> In current eix git master (>=eix-0.30.8) now the overlay path is not used, but instead the first overlay in the file is used. Moreover (since "gentoo.eix" contains no overlay at all), the file "gentoo.eix" is ignored.

OK. Thanks for your fixing.

I have waited about one month long. But dev.gentooexperimental.org doesn't come back. I think there are high possibility that the service has been shut down permanently.

**Comment by vaeth** [comment] 2015-06-03 18:42
closing since eix-0.30.8 is released. There's not much I can do about dev.gentooexperimental.org - for the time being, I will not throw out the option to use it.

**Closed by vaeth** 2015-06-03 18:42 UTC
